# Generated by Django 5.2.1 on 2025-06-13 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboutiqueapi', '0007_alter_product_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='Shop_profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='vendor_profile_pictures/'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='shop_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
