# Generated by Django 5.2.1 on 2025-08-26 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboutiqueapi', '0011_rename_price_product_base_price_productvariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_variants/'),
        ),
    ]
